// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: slowpizza.proto

package slowpizza

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	OrderItem(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
	OrderMultipleItems(ctx context.Context, opts ...grpc.CallOption) (Agent_OrderMultipleItemsClient, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) OrderItem(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, "/proto.Agent/OrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) OrderMultipleItems(ctx context.Context, opts ...grpc.CallOption) (Agent_OrderMultipleItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], "/proto.Agent/OrderMultipleItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentOrderMultipleItemsClient{stream}
	return x, nil
}

type Agent_OrderMultipleItemsClient interface {
	Send(*OrderRequest) error
	Recv() (*OrderReply, error)
	grpc.ClientStream
}

type agentOrderMultipleItemsClient struct {
	grpc.ClientStream
}

func (x *agentOrderMultipleItemsClient) Send(m *OrderRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentOrderMultipleItemsClient) Recv() (*OrderReply, error) {
	m := new(OrderReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	OrderItem(context.Context, *OrderRequest) (*OrderReply, error)
	OrderMultipleItems(Agent_OrderMultipleItemsServer) error
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) OrderItem(context.Context, *OrderRequest) (*OrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderItem not implemented")
}
func (UnimplementedAgentServer) OrderMultipleItems(Agent_OrderMultipleItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method OrderMultipleItems not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_OrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).OrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/OrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).OrderItem(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_OrderMultipleItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).OrderMultipleItems(&agentOrderMultipleItemsServer{stream})
}

type Agent_OrderMultipleItemsServer interface {
	Send(*OrderReply) error
	Recv() (*OrderRequest, error)
	grpc.ServerStream
}

type agentOrderMultipleItemsServer struct {
	grpc.ServerStream
}

func (x *agentOrderMultipleItemsServer) Send(m *OrderReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentOrderMultipleItemsServer) Recv() (*OrderRequest, error) {
	m := new(OrderRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderItem",
			Handler:    _Agent_OrderItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OrderMultipleItems",
			Handler:       _Agent_OrderMultipleItems_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "slowpizza.proto",
}
